name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/esphome/esphome

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Changes and Push
        run: |
          git checkout mymaster
          git merge upstream/dev
          git push origin mymaster
