name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository branch - dev
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: dev

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/esphome/esphome

      - name: Fetch Upstream Changes
        run: git fetch upstream dev

      - name: Merge Changes and Push
        run: |
          git checkout dev
          git merge upstream/dev
          git push origin dev

      - name: Checkout Forked Repository branch - udp_broadcast
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: udp_broadcast
      - name: Merge Changes and Push
        run: |
          git checkout udp_broadcast
          git merge origin/dev
          git push origin udp_broadcast
