name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/esphome/esphome

      - name: Fetch Upstream Changes
        run: git fetch upstream dev

      # is this the *right* way to do this?  who knows - but it seems to work...
      - name: Merge Changes and Push
        run: |
          git config --global user.email "29214674+juanboro@users.noreply.github.com"
          git config --global user.name "juanboro githubaction"
          git checkout --track origin/dev
          git merge --no-edit upstream/dev
          git push origin dev

          current_branches="esp32_soft_rmt fix_rc5_recv udp_broadcast"
          for branch in $current_branches
          do
            git checkout --track origin/$branch
            git merge --no-edit origin/dev
            git push origin $branch
          done
          git checkout mymaster
          for branch in $current_branches dev
          do
            git merge --no-ff --no-commit $branch || true
            git reset -- .github
            git commit -m "Merge branch: $branch into mymaster"
          done
          git push origin mymaster
